name: ModuleWeblateMerge

# SPDX-FileCopyrightText: 2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

# This file should be copied into each module that needs translating.
# Place in the .github/workflows/ directory in the default base branch.
# (Or in all active release/*, weblate/* and base branches if that is easier.)

run-name: "ModuleWeblateMerge ${{ github.run_number }}/${{ github.run_attempt }} (${{ github.event_name }}) by @${{ github.actor }}"

on:
  workflow_run:
    workflows:
      - 'ModuleWeblatePush'
    branches:
      - 'weblate/*'
    types:
      - 'completed'

permissions:
  contents: write
  pull-requests: read

jobs:
  wrap:
    uses: FreePBX/freepbx-ci-actions/.github/workflows/SharedWeblateMerge.yml@main
